server:
  port: 8081

management:
  endpoints:
    web:
      base-path: /

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: myGroup
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"